# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/175OeoNHJUIAqSTAKd8bQk6ua5tL932PL

Install Libraries
"""

import kagglehub

# Download latest version
path = kagglehub.dataset_download("nelgiriyewithana/global-weather-repository")

print("Path to dataset files:", path)

"""Load Dataset"""

pip install pandas numpy matplotlib seaborn scikit-learn statsmodels prophet xgboost lightgbm shap folium plotly kagglehub

import pandas as pd
df = pd.read_csv(f"{path}/GlobalWeatherRepository.csv")
df.head()

df.info()

df.describe()

df.shape

"""Data Cleaning"""

df.isnull().sum()

from sklearn.impute import SimpleImputer

num_cols = df.select_dtypes(include='number').columns

imputer = SimpleImputer(strategy='median')

df[num_cols] = imputer.fit_transform(df[num_cols])

cat_cols = df.select_dtypes(include='object').columns

for col in cat_cols:
    df[col].fillna(df[col].mode()[0], inplace=True)

"""Remove Duplicates"""

df.drop_duplicates(inplace=True)

"""Date Formatting"""

df['last_updated'] = pd.to_datetime(df['last_updated'])

"""Outlier Detection"""

import seaborn as sns
import matplotlib.pyplot as plt

plt.figure(figsize=(8,5))
sns.boxplot(df['temperature_celsius'])

"""Remove using IQR"""

Q1=df['temperature_celsius'].quantile(.25)
Q3=df['temperature_celsius'].quantile(.75)

IQR=Q3-Q1

lower=Q1-1.5*IQR
upper=Q3+1.5*IQR

df=df[(df.temperature_celsius>=lower)&
      (df.temperature_celsius<=upper)]

"""Normalization"""

from sklearn.preprocessing import StandardScaler

scaler=StandardScaler()

cols=['temperature_celsius',
      'humidity',
      'wind_kph',
      'pressure_mb']

df[cols]=scaler.fit_transform(df[cols])

"""Exploratory Data Analysis

Temperature Distribution
"""

sns.histplot(df['temperature_celsius'],bins=40)

"""Correlation Heatmap"""

plt.figure(figsize=(15,10))

sns.heatmap(df.corr(numeric_only=True),
            cmap='coolwarm')

"""Average Temperature by Country"""

country_temp=df.groupby("country")['temperature_celsius'].mean().sort_values(ascending=False).head(20)

country_temp.plot(kind='bar')

"""Rainfall Distribution"""

sns.scatterplot(data=df,
                x='humidity',
                y='precip_mm')

"""Monthly Trend"""

df['month']=df['last_updated'].dt.month

monthly=df.groupby('month')['temperature_celsius'].mean()

monthly.plot()

"""Time Series Forecasting

Use last_updated
"""

series=df.groupby("last_updated")['temperature_celsius'].mean()

series.plot(figsize=(14,5))

"""Train Test Split"""

train=series[:-30]

test=series[-30:]

"""ARIMA"""

from statsmodels.tsa.arima.model import ARIMA
import pandas as pd

model_arima=ARIMA(train,order=(5,1,2))
fit_arima=model_arima.fit()
# Assign to forecast_arima and reindex to align with 'test'
forecast_arima=pd.Series(fit_arima.forecast(30).values, index=test.index)

"""Evalution"""

from sklearn.metrics import mean_absolute_error

mae=mean_absolute_error(test,forecast_arima)

"""Prophet"""

from prophet import Prophet

prophet_df=series.reset_index()

prophet_df.columns=['ds','y']

model=Prophet()

model.fit(prophet_df)

"""Forecast"""

import pandas as pd
from prophet import Prophet

# Re-instantiate and fit the Prophet model to ensure 'model' is defined
prophet_df = series.reset_index()
prophet_df.columns = ['ds', 'y']
model = Prophet()
model.fit(prophet_df)

# Create future DataFrame with only the dates from the test set
future_prophet = pd.DataFrame({'ds': test.index})
forecast_prophet_df = model.predict(future_prophet)
# Assign 'yhat' column to forecast_prophet and ensure index alignment
forecast_prophet = pd.Series(forecast_prophet_df['yhat'].values, index=test.index)

"""XGBoost Regression"""

import pandas as pd
# Placeholder for forecast_xgb. You will need to replace this with actual XGBoost predictions.
# For now, it's a Series of zeros with the same index as the test set to allow the ensemble calculation to run.
forecast_xgb = pd.Series([0.0] * len(test), index=test.index)

for i in range(1,8):
    df[f'lag_{i}']=df['temperature_celsius'].shift(i)

"""Compare Models

| Model   | MAE | RMSE | MAPE |
| ------- | --- | ---- | ---- |
| ARIMA   |     |      |      |
| Prophet |     |      |      |
| XGBoost |     |      |      |

Ensemble Forecast
"""

from sklearn.metrics import mean_absolute_error

mae_prophet = mean_absolute_error(test, forecast_prophet)

print(f"Prophet MAE: {mae_prophet}")

sns.scatterplot(data=df,
                x='temperature_celsius',
                y='humidity')

"""Climate Analysis"""

df['year']=df['last_updated'].dt.year

df.groupby('year')['temperature_celsius'].mean().plot()

""" Air Quality Analysis"""

cols=['air_quality_PM2.5',
'air_quality_PM10',
'temperature_celsius',
'humidity']

sns.heatmap(df[cols].corr(),annot=True)

"""Sharp values"""

import shap
import xgboost as xgb
import pandas as pd

# Create a DataFrame from the series for XGBoost
df_xgb = series.to_frame(name='temperature_celsius')

# Create lagged features for XGBoost
for i in range(1, 8):
    df_xgb[f'lag_{i}'] = df_xgb['temperature_celsius'].shift(i)

# Drop rows with NaN values created by lagging
df_xgb.dropna(inplace=True)

# Define features (X) and target (y) for XGBoost
X = df_xgb[[f'lag_{i}' for i in range(1, 8)]]
y = df_xgb['temperature_celsius']

# Align the split with the existing train/test split for time series
# The 'test' variable corresponds to the last 30 observations of the original series.
# So, X_test and y_test should also correspond to the last 30 observations of the lagged series data.
X_train = X[:-len(test)]
X_test = X[-len(test):]
y_train = y[:-len(test)]
y_test = y[-len(test):]

# Train an XGBoost Regressor model
xgb_model = xgb.XGBRegressor(n_estimators=100, random_state=42)
xgb_model.fit(X_train, y_train)

# Assign the trained model to 'rf' as expected by the SHAP code
rf = xgb_model

# Generate SHAP values
explainer = shap.TreeExplainer(rf)
shap_values = explainer.shap_values(X_test)

# Plot SHAP summary
shap.summary_plot(shap_values, X_test)

"""Spatial Analysis"""

import plotly.express as px

fig=px.scatter_geo(
df,
lat='latitude',
lon='longitude',
color='temperature_celsius'
)

fig.show()

"""Country Comparison"""

country=df.groupby("country").agg({
'temperature_celsius':'mean',
'humidity':'mean',
'precip_mm':'mean'
})

country.head()

"""**Final Insights**

Include findings such as:

Average global temperature trends over time.
Regions with the highest and lowest temperatures.
Humidity and precipitation relationships.
Air quality indicators correlated with temperature and wind speed.
Anomalous weather events detected using Isolation Forest.
Comparison of forecasting models (ARIMA, Prophet, XGBoost).
Ensemble model performance improvements.
Feature importance showing key drivers of temperature prediction.
Geographical weather variations across countries and continents.
"""